name: Tests for opam-sysinstall
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        operating-system: [ macos-latest, ubuntu-latest ]
        ocaml-version: [ '4.11.1' ]
    runs-on: ${{ matrix.operating-system }}
    steps:
    - uses: actions/checkout@v2
    - uses: avsm/setup-ocaml@v1
      with:
        ocaml-version: ${{ matrix.ocaml-version }}
    - name: Pinning Package
      run: opam pin add -n -y .
    - name: Packages
      run: opam depext -yt opam-sysinstall
    - name: Dependencies
      run: opam install -t -y . --deps-only
    - name: Building
      run: opam exec -- dune build
    - name: Installing
      run: opam exec -- dune install
    - name: Install location
      run: mkdir -p $GITHUB_WORKSPACE/ocaml
    - name: Testing (dry run)
      run: opam exec -- opam sysinstall build --prefix=$GITHUB_WORKSPACE/ocaml --versions=4.12.0,4.10.2,4.07.1,4.04.1,4.02.3 --jobs=4 --dry-run
    - name: Testing
      run: opam exec -- opam sysinstall build --prefix=$GITHUB_WORKSPACE/ocaml --versions=4.12.0,4.10.2,4.07.1,4.04.1,4.02.3 --jobs=4
    - name: Inspecting
      run: |
        echo "let () = print_endline Sys.ocaml_version" > main.ml
        $GITHUB_WORKSPACE/ocaml/4.12.0/bin/ocamlopt main.ml -o twelve.out
        ./twelve.out
        $GITHUB_WORKSPACE/ocaml/4.10.2/bin/ocamlopt main.ml -o ten.out
        ./ten.out
        $GITHUB_WORKSPACE/ocaml/4.07.1/bin/ocamlopt main.ml -o seven.out
        ./seven.out
        $GITHUB_WORKSPACE/ocaml/4.04.1/bin/ocamlopt main.ml -o four.out
        ./four.out
        $GITHUB_WORKSPACE/ocaml/4.02.3/bin/ocamlopt main.ml -o two.out
        ./two.out
